// portfolio/src/layout/About.jsx
import React from 'react'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import { Link } from 'react-router-dom'
import '../App.css'
function About() {
return <div className="pageLayout">
<Nav/>
<div className="content">  
<div className='aboutWrapper'>
  <h2>Florida based software engineer.</h2>
  <p>
    After studying computer science at UCF, I've been working with <a href="https://www.fulcraevents.com/" target='_blank'>Fulcra</a>.
    <br/> I've been producing live/hybrid events.
    <br />Now I'm seeking a software engineering role.
    <br />
  </p>    
  <p>
    Throughout the years I've built several applications. 
    <br/>Some of which you can view on my <Link to="/Portfolio">portfolio</Link>.
  </p>
</div>
</div>
<Footer/>  
</div>;
}

export default About

// app/src/routes/about/+page.svelte
<script>
  import Nav from "../../components/Nav.svelte";
  import ContactLinks from "../../components/ContactLinks.svelte";
  import "../../style/style.css";
</script>

<main>
  <Nav />
  <div class="content">
    <h1>Florida based software engineer.</h1>
    <p>
      Throughout the years I've built several web apps. Some of which you can
      view on my <a href="/work">portfolio</a>.
      <br />
      The past few years I've been focused on producing live/hybrid events.
      <br />
      Now I'm seeking a technical role.
      <br />
    </p>
  </div>
  <ContactLinks />
</main>

<style>
  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }
  @media (min-width: 640px) {
    main {
      max-width: none;
    }
  }
  h1 {
    text-transform: uppercase;
    font-size: 3em;
    font-weight: 100;
  }
  .content {
    height: 160px;
  }

  p {
    color: #f7ffe5;
  }
  p a {
    color: #f7ffe5;
  }

  p a:hover {
    color: #a0c49d;
  }
</style>
