// app/src/routes/resume/+page.svelte
<script>
  import Nav from "../../components/Nav.svelte";
  import Resume from "../../Resume.pdf";
</script>

<main>
  <Nav />
  <embed class="portfolio" type="application/pdf" src={Resume} />
</main>

<style>
  main {
    text-align: center;
    padding: 1em;
    /* max-width: 440px; */
    margin: 0 auto;
  }

  .portfolio {
    height: 800px;
    width: 800px;
  }

  embed:focus {
    outline: none;
  }
</style>

// portfolio/src/layout/Resume.jsx
import React from 'react'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import PDF from '../images/Resume.pdf'
function Resume() {
  return <div className="pageLayout">
  <Nav/>
  <div className="content">  
    <embed class="resume" type="application/pdf" src={PDF} />
  </div>
  <Footer/>  
</div>;
}

export default Resume
